### ISSUE TITLE
Find max WTS and min WTB

### ISSUE THREAD

**Issue by SeanFricke** [SeanFricke/TradeGatherer#10]
### TODO

- [x] Iterate through list of order dataframes from #9 and find the mean of each using the method from #5
- [x] Find the minimum average priced item if WTB, and the maximum average priced item if WTS
- [x] Return the item name from the above result
- [x] Create tests of new features where applicable

### Scope

- `database.py`
   - `getMeanPlat` method call to find the mean of each item
   - Method from #9 to get list of selected item's orders
