### ISSUE TITLE
Add concurrency to item search

### ISSUE THREAD

**Issue by SeanFricke** [SeanFricke/TradeGatherer#13]
### TODO

- [x] Implement AsyncIO into `API.getItemOrders` method.
- [x] Make concurrency with above function as a coroutine in `Database.searchItems` method.
- [x] Await each task seperately, do not gather.
- [x] Add implementation for a loading bar/"n complete" fraction/percent complete with each item completion being logged and stated.

### Scope

- `api.py`
   - `getItemOrders` method 
- `database.py`
   - `searchItems` method
