### ISSUE TITLE
Take in search items list and pull order list from each

### ISSUE THREAD

**Issue by SeanFricke** [SeanFricke/TradeGatherer#9]
### TODO

- [x] Make a new method to take in _n_ amounts of selected items as args
- [x] Iterate through the selected items and get the order listings of each
- [x] Save into an iterable list of dataframes of each item's listings.
- [x] Create tests for implemented features where applicable

### Scope

- `database.py`
   -`getOrderDF` method call for getting listings of each item
   - New method for taking in selected items and getting the listings of each
- `test_main.py`
   - New tests for checking results and outputs of any features added
